"""
    This module provides test data
"""

URLS = """
https://www.google.com
https://www.wikipedia.org
https://www.youtube.com
https://www.facebook.com
https://www.amazon.com
https://www.twitter.com
https://www.instagram.com
https://www.reddit.com
https://www.linkedin.com
https://www.apple.com
https://www.netflix.com
https://www.microsoft.com
https://www.yahoo.com
https://www.bing.com
https://www.pinterest.com
https://www.quora.com
https://www.spotify.com
https://www.twitch.tv
https://www.snapchat.com
https://www.github.com
https://www.stackoverflow.com
https://www.ebay.com
https://www.wikipedia.org/wiki/Main_Page
https://www.nytimes.com
https://www.cnn.com
https://www.bbc.com
https://www.theguardian.com
https://www.dailymotion.com
https://www.vimeo.com
https://www.tumblr.com
https://www.flickr.com
https://www.medium.com
https://www.gitlab.com
https://www.wix.com
https://www.trello.com
https://www.slack.com
https://www.dropbox.com
https://www.zendesk.com
https://www.indeed.com
https://www.airbnb.com
https://www.vogue.com
https://www.buzzfeed.com
https://www.forbes.com
https://www.washingtonpost.com
https://www.time.com
https://www.huffpost.com
https://www.squarespace.com
https://www.washington.edu
https://www.sciencedirect.com
https://www.smithsonianmag.com
https://www.nationalgeographic.com
https://www.popularmechanics.com
https://www.cnbc.com
https://www.theverge.com
https://www.engadget.com
https://www.mashable.com
https://www.techcrunch.com
https://www.businessinsider.com
https://www.reuters.com
https://www.npr.org
https://www.smithsonian.edu
https://www.aclu.org
https://www.aol.com
https://www.buzzfeednews.com
https://www.bbc.co.uk
https://www.apnews.com
https://www.nike.com
https://www.adidas.com
https://www.underarmour.com
https://www.reebok.com
https://www.samsung.com
https://www.lenovo.com
https://www.hp.com
https://www.dell.com
https://www.rubyredinc.com
https://www.vizio.com
https://www.sony.com
https://www.walmart.com
https://www.target.com
https://www.costco.com
https://www.bestbuy.com
https://www.homeDepot.com
https://www.lowes.com
https://www.kroger.com
https://www.publix.com
https://www.aldi.us
https://www.wholefoodsmarket.com
https://www.cvs.com
https://www.riteaid.com
https://www.safeway.com
https://www.homedepot.com
https://www.etsy.com
https://www.houzz.com
https://www.lowe's.com
https://www.wayfair.com
https://www.bedbathandbeyond.com
https://www.potterybarn.com
https://www.crateandbarrel.com
"""
